version: '3'

services:
  db_translator:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: "Postgres2020!"
    ports:
      - "54320:5432"
    volumes:
      - ./data_translator:/var/lib/postgresql/data
  db_document:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: "Postgres2020!"
    ports:
      - "54321:5432"
    volumes:
      - ./data_document:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - db_translator
      - db_document
  translator_api:
    image: gradle:6.3.0-jdk11
    ports:
      - "8080:8080"
    working_dir: /code
    volumes:
      - ./translatorCRUD:/code
    depends_on:
      - db_translator
    command: >
        bash -c "./gradlew bootJar
        && ./gradlew bootRun"
    network_mode: "host"
  document_searcher:
    image: gradle:6.3.0-jdk11
    ports:
      - "8081:8081"
    working_dir: /code
    volumes:
      - ./documentSearcher:/code
    depends_on:
      - db_document
    command: >
        bash -c "./gradlew bootJar
        && ./gradlew bootRun"
    network_mode: "host"
